# Generated by Django 5.0 on 2023-12-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
